python inference.py \
--image_dir inputs/b0 \
--out_dir outputs/b0 \
--mode 'sparse_view_horiz' \
--bg_trd 0.2 \
--ckpt_path ./checkpoints/model_sparse.ckpt \
--config configs/inference_pvd_1024.yaml \
--ddim_steps 50 \
--video_length 25 \
--device 'cuda:0' \
--height 576 --width 1024 \
--model_path ./checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth